name: 'pipeline'

on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - 'main'
    types:
      - 'opened'
      - 'synchronize'

jobs:
  deployment_pipeline:
    runs-on: ubuntu-24.04
    env:
      PORT: 3000
      JWT_SECRET: ${{ secrets.JWT_SECRET }}
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 10
      - uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Installing dependencies
        run: pnpm i --frozen-lockfile
      - name: Running linting
        run: pnpm lint
      - name: Running unit tests
        env:
            TEST_URI: ${{ secrets.TEST_URI }}
        run: pnpm unitTest

      - name: Installing frontend dependencies
        run: pnpm i --frozen-lockfile
        working-directory: ./Redux_FrontEnd
      - name: Running frontend linting
        run: pnpm lint
        working-directory: ./Redux_FrontEnd
      - name: Running frontend unit tests
        env:
          TEST_URI: ${{ secrets.TEST_URI }}
        run: pnpm test
        working-directory: ./Redux_FrontEnd
      - name: Building frontend
        run: pnpm build
        working-directory: ./Redux_FrontEnd

      - name: Installing E2E dependencies
        run: pnpm i --frozen-lockfile
        working-directory: ./E2E
      - name: Installing E2E browsers
        run: npx playwright install chromium --with-deps
        working-directory: ./E2E
      - name: Running E2E tests
        env:
          TEST_URI: ${{ secrets.TEST_URI }}
        run: pnpm test
        working-directory: ./E2E
        
      - name: Deploy to render
        if: ${{ github.event_name == 'push' }}
        run: curl https://api.render.com/deploy/srv-${{secrets.RENDER_SERVICE_ID}}?key=${{secrets.RENDER_API_KEY}}
        
      - name: Send success notification
        if: ${{ success() && github.event_name == 'push' }}
        uses: stegzilla/discord-notify@v2
        with:
          webhook_url: ${{ secrets.DISCORD_WEBHOOK_URL }}
          title: New build deployed
          message: |
            **Event:** ${{ github.event_name }}
            **Repo:** ${{ github.event.repository.full_name }}
            **Ref:** ${{ github.event.ref }}
            **Workflow:** ${{ github.workflow }}
            **Author:** ${{ github.event.head_commit.author.name }}
            **Committer:** ${{ github.event.head_commit.committer.name }}
            **Pusher:** ${{ github.event.pusher.name }}
            **Pusher Date:** ${{ github.event.pusher.date }}
            **Commit URL:** ${{ github.event.head_commit.url }}
            **Commit Message:** ${{ github.event.head_commit.message }}
          include_image: true
          avatar_url: "https://images-wixmp-ed30a86b8c4ca887773594c2.wixmp.com/f/9c870380-219a-4060-914d-9929082d5056/dfghzab-31509847-d454-4602-ac9b-0b1ad48ba9b7.png/v1/fill/w_600,h_600,q_80,strp/build_chan_by_lupinmk_dfghzab-fullview.jpg?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1cm46YXBwOjdlMGQxODg5ODIyNjQzNzNhNWYwZDQxNWVhMGQyNmUwIiwiaXNzIjoidXJuOmFwcDo3ZTBkMTg4OTgyMjY0MzczYTVmMGQ0MTVlYTBkMjZlMCIsIm9iaiI6W1t7ImhlaWdodCI6Ijw9NjAwIiwicGF0aCI6IlwvZlwvOWM4NzAzODAtMjE5YS00MDYwLTkxNGQtOTkyOTA4MmQ1MDU2XC9kZmdoemFiLTMxNTA5ODQ3LWQ0NTQtNDYwMi1hYzliLTBiMWFkNDhiYTliNy5wbmciLCJ3aWR0aCI6Ijw9NjAwIn1dXSwiYXVkIjpbInVybjpzZXJ2aWNlOmltYWdlLm9wZXJhdGlvbnMiXX0.PsmFPEaVbfDMhXGlNbGe7Jmku2lwgnw2blRzAxsKL-U"
          username: BuildNotifier-chan
          colour: "#32E638"
      - name: Send failure notification
        if: ${{ failure() && github.event_name == 'push' }}
        uses: stegzilla/discord-notify@v2
        with:
          webhook_url: ${{ secrets.DISCORD_WEBHOOK_URL }}
          title: New build failed
          message: |
            **Event:** ${{ github.event_name }}
            **Repo:** ${{ github.event.repository.full_name }}
            **Ref:** ${{ github.event.ref }}
            **Workflow:** ${{ github.workflow }}
            **Author:** ${{ github.event.head_commit.author.name }}
            **Committer:** ${{ github.event.head_commit.committer.name }}
            **Pusher:** ${{ github.event.pusher.name }}
            **Pusher Date:** ${{ github.event.pusher.date }}
            **Commit URL:** ${{ github.event.head_commit.url }}
            **Commit Message:** ${{ github.event.head_commit.message }}
          include_image: true
          avatar_url: "https://images-wixmp-ed30a86b8c4ca887773594c2.wixmp.com/f/9c870380-219a-4060-914d-9929082d5056/dfghzab-31509847-d454-4602-ac9b-0b1ad48ba9b7.png/v1/fill/w_600,h_600,q_80,strp/build_chan_by_lupinmk_dfghzab-fullview.jpg?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1cm46YXBwOjdlMGQxODg5ODIyNjQzNzNhNWYwZDQxNWVhMGQyNmUwIiwiaXNzIjoidXJuOmFwcDo3ZTBkMTg4OTgyMjY0MzczYTVmMGQ0MTVlYTBkMjZlMCIsIm9iaiI6W1t7ImhlaWdodCI6Ijw9NjAwIiwicGF0aCI6IlwvZlwvOWM4NzAzODAtMjE5YS00MDYwLTkxNGQtOTkyOTA4MmQ1MDU2XC9kZmdoemFiLTMxNTA5ODQ3LWQ0NTQtNDYwMi1hYzliLTBiMWFkNDhiYTliNy5wbmciLCJ3aWR0aCI6Ijw9NjAwIn1dXSwiYXVkIjpbInVybjpzZXJ2aWNlOmltYWdlLm9wZXJhdGlvbnMiXX0.PsmFPEaVbfDMhXGlNbGe7Jmku2lwgnw2blRzAxsKL-U"
          username: BuildNotifier-chan
          colour: "#F02E23"

  tag_release:
    needs:
      - deployment_pipeline
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - name: Bump version and push tag
        if: ${{ github.event_name == 'push' && contains(github.event.commits[0].message , '#tag' ) }}
        uses: anothrNick/github-tag-action@1.71.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BUMP: patch
